# This is a sample build configuration for Java (Gradle).
# Check our guides at https://confluence.atlassian.com/x/zd-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: openjdk:11

pipelines:
  default:
    - step:
        name: Deploy version
        deployment: production
        caches:
          - gradle
        script:
          - bash ./gradlew shadowjar
          - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"./build/libs/Skron-nightly-all.jar"

    - step:
        name: Deploy code to Github
        deployment: Deploy to Github
        script:
          - git config --global user.email "${GITHUB_EMAIl}"
          - git config --global user.name "Olyno"
          - git remote set-url origin https://Olyno:${GITHUB_TOKEN}@github.com/Olyno/Skron.git
          - git push origin master --force

definitions:
  caches:
    gradlewrapper: ~/.gradle/wrapper